# Generated by Django 3.2.7 on 2021-10-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211023_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spam_subscribe',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
